project:
  type: website

website:
  title: "The big beautiful website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EduVit
format:
  html:
    theme: cosmo
    from: markdown+emoji
    css: styles.css



