project:
  type: website

website:
  title: "The big beautiful website"
  navbar:
    left:
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/EduVit
format:
  html:
    theme: cosmo
    from: markdown+emoji
    css: styles.css
    link-external-newwindow: true



